# Generated by Django 3.1.1 on 2020-09-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
