# Generated by Django 3.1.1 on 2020-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='question', max_length=50),
            preserve_default=False,
        ),
    ]
