# Generated by Django 3.1.1 on 2020-09-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num',
        ),
    ]
